branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
  - cd NodIO-Client && perl Build.PL && ./Build 
install:
  - ./Build installdeps --cpan_client cpanm

script: "./Build test"